name: Swift

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cd SingleAppGit
        bundle install
        bundle exec fastlane buildLane
    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: derivedData/Build/Products/Debug-iphonesimulator/SingleAppGit.app
    - name: Upload runner
      uses: actions/upload-artifact@v1
      with:
        name: runner
        path: derivedData/Build/Products/Debug-iphonesimulator/SingleAppGitUITests-Runner.app
        
  unitTests:
    needs: build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download build results
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: derivedData/Build/Products/Debug-iphonesimulator/SingleAppGit.app
    - name: Run unit tests
      run: |
        cd SingleAppGit
        bundle exec fastlane unitTestLane
        
  uiTests:
    needs: build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download build results
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: derivedData/Build/Products/Debug-iphonesimulator/SingleAppGit.app
    - name: Download runner
      uses: actions/upload-artifact@v1
      with:
        name: runner
        path: derivedData/Build/Products/Debug-iphonesimulator/SingleAppGitUITests-Runner.app
    - name: Run UI tests
      run: |
        cd SingleAppGit
        bundle exec fastlane uiTestLane
