name: Swift

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup bundle script
      run:  |
        gem install bundler
        gem update bundler
        bundle install
    - name: Run tests
      run: bundle exec faslane testLane
